# Generated by Django 6.1 on 2026-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('posting_date', models.DateField()),
                ('apply_link', models.URLField()),
                ('skills_text', models.TextField(blank=True)),
            ],
        ),
    ]
